export enum GameNames {
  Millionaire = 'Who Wants to Be a Millionaire?',
  BubbleShooter = 'Arkadium\'s Bubble Shooter',
  FamilyFeud = 'Family Feud',
  WordWipe = 'Arkadium Word Wipe Game',
  SolitaireKitchen = 'Solitaire Kitchen: Tripeaks Cooking Adventure',
  Outspell = 'Outspell Spelling Game',
  CrystalCollapse = 'Crystal Collapse',
  MahjonggSolitaire = 'Mahjongg Solitaire',
  PriceIsRightPlinko = 'The Price Is Right Plinko Pegs',
  BlockChamp = 'Block Champ',
  Lumeno = 'Lumeno',
  EightBallPool = '8 Ball Pool',
  KlondikeSolitaire = 'Klondike Solitaire',
  MahjonggDimensionsBlue = 'Mahjongg Dimensions Blue',
  MahjonggCandy = 'Mahjongg Candy',
  JewelShuffle = 'Jewel Shuffle',
  Bridge = 'Free Online Bridge',
  FreecellSolitaire = 'Freecell Solitaire',
  CardSharks = 'Card Sharks',
  DailyCrossword = 'Free Online Daily Crossword Puzzle',
  CrystalCollapseOdyssey = 'Crystal Collapse Odyssey',
  CrystalCollapseSummerNights = 'Crystal Collapse Summer Nights'
}
