export enum GamePaths {
  Millionaire = 'millionaire',
  BubbleShooter = 'bubble-shooter',
  FamilyFeud = 'family-feud',
  WordWipe = 'word-wipe',
  SolitaireKitchen = 'solitaire-kitchen',
  Outspell = 'outspell',
  CrystalCollapse = 'crystal-collapse',
  MahjonggSolitaire = 'mahjongg-solitaire',
  PriceIsRightPlinko = 'price-is-right-plinko',
  BlockChamp = 'block-champ',
  Lumeno = 'lumeno',
  EightBallPool = 'free-8-ball-pool',
  KlondikeSolitaire = 'klondike-solitaire',
  MahjonggDimensionsBlue = 'mahjongg-dimensions-blue',
  MahjonggCandy = 'mahjongg-candy',
  JewelShuffle = 'jewel-shuffle',
  Bridge = 'bridge',
  FreecellSolitaire = 'free-freecell-solitaire',
  CardSharks = 'card-sharks',
  DailyCrossword = 'daily-crossword',
  CrystalCollapseOdyssey = 'crystal-collapse-odyssey',
  CrystalCollapseSummerNights = 'crystal-collapse-summer-nights'
}
