name: Cypress Tests

on: [workflow_dispatch]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Write the cypress.env.json file
        run: |
          echo '${{ secrets.cypress}}' > cypress.env.json

      - name: Run Cypress Tests 
        uses: cypress-io/github-action@v4

      #Artifacts
      - uses: actions/upload-artifact@v2
        name: Upload screenshots in case of fail
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress
      
      - name: Upload MochaAwesome reports
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: MochaAwesome Reports
          path: ./cypress/results

      - uses: actions/upload-artifact@v2
        name: Upload videos in case of failure
        if: failure()
        with:
          name: cypress-videos
          path: cypress
